In [1]:
import pandas as pd
from datetime import datetime

In [2]:
df_all = pd.read_csv('all-jobs.csv')
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3302 entries, 0 to 3301
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AY           3302 non-null   object
 1   Institution  3302 non-null   object
 2   Position     3302 non-null   object
 3   Address      3302 non-null   object
 4   Link         3158 non-null   object
 5   TrackType    3302 non-null   object
 6   DateAdded    3302 non-null   object
dtypes: object(7)
memory usage: 180.7+ KB

In [3]:
df_combined = pd.read_csv('combined-jobs.csv')
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3344 entries, 0 to 3343
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AY                3344 non-null   object
 1   Institution       3344 non-null   object
 2   Position          3344 non-null   object
 3   Address           3344 non-null   object
 4   Link              3187 non-null   object
 5   TrackType         3344 non-null   object
 6   DateAdded         3344 non-null   object
 7   DateTimeObj       3344 non-null   object
 8   Latitude          3344 non-null   float64
 9   Longitude         3344 non-null   float64
 10  FormattedAddress  3344 non-null   object
 11  City              3276 non-null   object
 12  County            3016 non-null   object
 13  State             3319 non-null   object
 14  StateCode         3212 non-null   object
 15  Country           3343 non-null   object
 16  CountryCode       3344 non-null   object
dtypes: float64(2), object(15)
memory usage: 444.2+ KB

## Show Difference Between Two DataFrames

In [4]:
df_diff = df_all.merge(df_combined, indicator = True, how='left').loc[lambda x : x['_merge']!='both']
df_diff

,AY,Institution,Position,Address,Link,TrackType,DateAdded,DateTimeObj,Latitude,Longitude,FormattedAddress,City,County,State,StateCode,Country,CountryCode,_merge
2118,2019-2020,American U of Beirut,"Faculty Positions, the Communication Skills Pr...","Beirut, Lebanon 1107 2020",https://www.aub.edu.lb/fas/Pages/academic-empl...,Unavailable,11/02/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2122,2019-2020,Virginia Tech,Assistant Professor of Rhetoric and Writing/PT...,"Blacksburg, VA 24060",https://jobs.vt.edu/careers.html,TT,08/29/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2130,2019-2020,"U of Massachusetts, Boston",Assistant Professor of English (in Composition...,"Boston, MA 02125",http://employmentopportunities.umb.edu/boston/...,TT,09/18/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2141,2019-2020,"U of Tennessee, Chattanooga",TT Assistant Professor of Civic Rhetoric & Pub...,"Chattanooga, TN 37403",https://ut.taleo.net/careersection/utc_faculty...,TT,11/03/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2165,2019-2020,U of Oregon,"Associate or Full Professor, Composition, Rhet...","Eugene, OR 97403",https://academicjobsonline.org/ajo/jobs/14377,TT,09/09/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2025-2026,Valdosta SU,Assistant Professor - English\n,"Valdosta, GA 31698",https://joblist.mla.org/job/2000788/assistant-...,TT,12/18/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3365,2025-2026,Georgia Tech,"Academic Professional (Associate Director, Wri...","Atlanta, GA 30332",https://careers.hprod.onehcm.usg.edu/psc/caree...,NTT,02/10/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3380,2026-2027,Brigham Young University,"Professional Writing, Rhetoric, or English Tea...","Provo, UT",Link,TT,08/17/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3385,2026-2027,Park U,Writing Center and English Language Learner Se...,"Parkville, MO",https://park.wd1.myworkdayjobs.com/en-US/ParkU...,NTT,08/21/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3387,2026-2027,Marist U,"Assistant Professor of English, Technical and ...","Poughkeepsie, NY 12601",https://careers.marist.edu/cw/en-us/job/494061...,TT,08/26/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [5]:
df_diff.Institution.values.tolist()

['American U of Beirut',
 'Virginia Tech',
 'U of Massachusetts, Boston',
 'U of Tennessee, Chattanooga',
 'U of Oregon',
 'Mount Saint Vincent U \n',
 'U of North Florida',
 'Christian Brothers U',
 "Saint Mary's C of California",
 'New York U',
 'U of Central Florida',
 'U of Pittsburgh',
 'U of South Florida Sarasota-Manatee',
 'Hamline U',
 'York U',
 'York U',
 'U of Arizona',
 'Baylor U',
 'Brandeis U',
 'Midwestern SU, Texas',
 'Virginia Tech',
 'U of Dayton',
 'Francis Marion U',
 'U of California, San Diego',
 'U of Louisville',
 'U of Puerto Rico, Mayagüez',
 'U of Toronto Mississauga',
 'U of Toronto Mississauga',
 'Auburn U, Montgomery',
 'Fordham U',
 'Saint Louis U',
 'U of British Columbia',
 'U of South Dakota',
 'Gallaudet U',
 'Gallaudet U',
 'Gallaudet U',
 'York U',
 'York U',
 'Emory U',
 'Indiana U Bloomington',
 'Northeastern U',
 'U of Illinois, Chicago',
 'U of Cincinnati\n',
 'Claremont McKenna C',
 'U of Massachusetts, Dartmouth\n',
 'U of North Texas',
 'Wayne SU\n',
 'Duke U',
 'U of Texas Rio Grande Valley',
 'Elon U',
 'Texas Christian U',
 'James Madison U',
 'Montana SU-Northern',
 'Michigan Tech U',
 'Cornell U',
 'Kennesaw SU',
 'California SU, Long Beach',
 'Texas Tech U',
 'Christian Brothers U',
 'Middle Tennessee SU',
 'Middle Tennessee SU',
 'Utah Valley U',
 'Queens C, CUNY \n',
 'U of Nevada, Reno',
 'U of Utah',
 'Palomar C',
 'U of Washington',
 'American U of Sharjah',
 'Saint Louis U',
 'C of Staten Island, CUNY',
 'U of Tampa',
 'Arizona SU',
 'Towson U',
 'U of Alabama',
 'Iowa SU',
 'Johns Hopkins U',
 'Messina C and Boston C',
 'C of Charleston',
 'U of South Carolina, Columbia',
 'U of Copenhagen',
 'Texas A&M U, Corpus Christi',
 'Emory U Oxford C',
 'Embry-Riddle Aeronautical U',
 'North Dakota SU',
 'North Dakota SU',
 'Sam Houston SU',
 'Jacksonville SU',
 'U of Wisconsin-Madison',
 'SUNY New Paltz',
 'Weber SU',
 'Univesity of Central Florida',
 'U of California, Santa Barbara',
 'UIUC',
 'Gordon C',
 'Penn State York',
 'U of Michigan',
 'Emory U \n',
 'U of Tennessee, Chattanooga\n',
 'Davidson C',
 'Glenville SU',
 'Trinity C',
 'Northern Kentucky U',
 'Jacksonville SU',
 'U of Wyoming',
 'U of California, Los Angeles',
 'Texas Tech U',
 'U of Memphis',
 'North Central C',
 'Emory U Oxford C',
 'Bradley U',
 'U of Nevada, Reno',
 'California Polytechnic SU',
 'Florida SU',
 'Arizona SU',
 'Towson U',
 'Villanova U',
 'U of Northern Colorado',
 'Georgia Tech',
 'Chapman U',
 'Western Michigan U',
 'Salt Lake Community C',
 'Haverford C',
 'Massachusetts Maritime Academy',
 'Carnegie Mellon U',
 'Francis Marion U',
 'U of Texas, El Paso',
 'U of South Alabama',
 'High Point U',
 'Western Kentucky U',
 'Colorado Mesa University',
 'The University of Texas Rio Grande Valley',
 'Georgia Southwestern SU',
 'Valdosta SU',
 'Georgia Tech',
 'Brigham Young University',
 'Park U',
 'Marist U']

## Create TrackType Data SubSet

Write a new file with per date sum of job type post counts:

{date, posts: INT total of TT, type: "TT"},
{date, posts: INT total of NTT, type: "NTT"},
{date, posts: INT total of Unavailable, type: "Unavailable"},

In [6]:
def create_subset(df, subset_col_1, subset_col_dates):
  '''
  # @create_subset: Create subsets of TrackType data

  # Params
  - df: pandas DataFrame. Data set with all parameters of interest
  - subset_col: String. Column of interest.
  
  ## Return
  - new_df: pandas DataFrame. New dataframe with following structure per row: 
    - date: DateTime Obj of posting date.
    - type: String. Type of track: TT, NTT, Unavailable.
    - posts: Integer. Total sum of posts of that type of job on that specific date.
  '''
  uniq_subset_col_values = df[subset_col_1].unique()
  uniq_subset_col_dates = sorted(df[subset_col_dates].apply(lambda d: datetime.strptime(d,'%m/%d/%Y')).unique())
  list_unique_dates_sorted = []
  for date in uniq_subset_col_dates:
    list_unique_dates_sorted.append(date.strftime("%m/%d/%Y"))

  list_record_rows_per_date = []
  list_record_rows_flat = []
  for date_str in list_unique_dates_sorted:
    if date_str != '01/01/1900':
      date_slice = df.loc[df.DateAdded == date_str]
      list_record_rows_per_date.append({
        'date': date_str,
        'datetimeObj': datetime.strptime(date_str, '%m/%d/%Y'),
        'TT': len(date_slice.loc[date_slice.TrackType == 'TT']),
        'NTT': len(date_slice.loc[date_slice.TrackType == 'NTT']),
        'Unavailable': len(date_slice.loc[date_slice.TrackType == 'Unavailable']),
        'Total': len(date_slice.loc[date_slice.TrackType == 'TT'])+len(date_slice.loc[date_slice.TrackType == 'NTT'])+len(date_slice.loc[date_slice.TrackType == 'Unavailable'])
      })

      for tt in uniq_subset_col_values:
        tt_date_slice = date_slice.loc[date_slice.TrackType == tt]
        list_record_rows_flat.append({
          'date': date_str,
          'datetimeObj': datetime.strptime(date_str, '%m/%d/%Y'),
          'type': tt,
          'posts': len(tt_date_slice)
        })
  df_new_flat = pd.DataFrame(list_record_rows_flat)
  df_new_per_date = pd.DataFrame(list_record_rows_per_date)
  # Add moving averages
  df_new_flat['Overall_EMA'] = df_new_flat['posts'].ewm(span=7).mean()        # Exponential Moving Average
  df_new_per_date['Overall_EMA'] = df_new_per_date['Total'].ewm(span=7).mean()        # Exponential Moving Average
  return {
    'df_new_flat': df_new_flat,
    'df_new_per_date': df_new_per_date,
  }

In [7]:
df__tt_per_date_flat = create_subset(df_combined, subset_col_1='TrackType', subset_col_dates='DateAdded')
df__tt_per_date_flat['df_new_per_date'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1123 entries, 0 to 1122
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         1123 non-null   object
 1   datetimeObj  1123 non-null   datetime64[ns]
 2   TT           1123 non-null   int64
 3   NTT          1123 non-null   int64
 4   Unavailable  1123 non-null   int64
 5   Total        1123 non-null   int64
 6   Overall_EMA  1123 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 61.5+ KB

In [8]:
df__tt_per_date_flat['df_new_per_date'].head()

         date datetimeObj  TT  NTT  Unavailable  Total  Overall_EMA
0  09/15/2012  2012-09-15   0    1            0      1     1.000000
1  01/15/2013  2013-01-15   0    1            0      1     1.000000
2  01/20/2013  2013-01-20   0    1            0      1     1.000000
3  01/23/2013  2013-01-23   2    0            0      2     1.365714
4  01/24/2013  2013-01-24   1    0            0      1     1.245839

In [9]:
df__tt_per_date_flat['df_new_flat'].to_csv('tt-per-date-flat.csv', index=False)

In [10]:
df__tt_per_date_flat['df_new_per_date'].to_csv('tt-per-date.csv', index=False)